# Generated by Django 2.1.4 on 2018-12-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmDat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_info', models.CharField(max_length=50)),
                ('serv_info', models.CharField(max_length=50)),
                ('cpu_info', models.CharField(max_length=50)),
                ('disk_info', models.CharField(max_length=50)),
                ('mem_info', models.CharField(max_length=50)),
                ('load_info', models.CharField(max_length=50)),
                ('mark_info', models.CharField(blank=True, default='BEIJING_IDC', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
