# Generated by Django 2.1.4 on 2018-12-26 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mydjangoapp', '0002_registeruser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterUser',
        ),
    ]
