# Generated by Django 2.1.4 on 2018-12-30 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mydjangoapp', '0003_delete_registeruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=64, null=True, verbose_name='挂载路径')),
                ('size', models.CharField(blank=True, max_length=16, null=True, verbose_name='磁盘大小/G')),
                ('remarks', models.CharField(blank=True, max_length=2048, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '磁盘表',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, max_length=64, null=True, verbose_name='阿里云主机名')),
                ('ecsname', models.CharField(blank=True, max_length=64, null=True, verbose_name='阿里云实例ID')),
                ('login_port', models.CharField(blank=True, default='22', max_length=16, null=True, verbose_name='ssh登录端口')),
                ('cpu', models.CharField(blank=True, max_length=8, null=True, verbose_name='CPU')),
                ('mem', models.CharField(blank=True, max_length=8, null=True, verbose_name='内存/M')),
                ('speed', models.CharField(blank=True, default='5', max_length=8, null=True, verbose_name='带宽/M')),
                ('eth1_network', models.CharField(blank=True, max_length=32, null=True, verbose_name='公网IP')),
                ('eth0_network', models.CharField(max_length=32, verbose_name='私网IP')),
                ('sn', models.CharField(blank=True, max_length=64, null=True, verbose_name='sn')),
                ('kernel', models.CharField(blank=True, max_length=64, null=True, verbose_name='系统内核')),
                ('remarks', models.CharField(blank=True, max_length=2048, null=True, verbose_name='备注')),
                ('createtime', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建时间')),
                ('expirytime', models.CharField(blank=True, max_length=32, null=True, verbose_name='到期时间')),
                ('state', models.SmallIntegerField(blank=True, choices=[(1, 'Running'), (2, '下线'), (3, '关机'), (4, '删除')], null=True, verbose_name='主机状态')),
                ('disks', models.ManyToManyField(blank=True, null=True, to='Mydjangoapp.Disk', verbose_name='磁盘')),
            ],
            options={
                'verbose_name_plural': '主机表',
            },
        ),
        migrations.CreateModel(
            name='Lable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True, verbose_name='标签')),
            ],
            options={
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_name', models.CharField(default='root', max_length=16, verbose_name='登录用户名')),
                ('login_pwd', models.CharField(blank=True, max_length=64, null=True, verbose_name='登录密码')),
                ('auth', models.CharField(blank=True, max_length=8, null=True, verbose_name='具有权限')),
            ],
            options={
                'verbose_name_plural': '主机用户表',
            },
        ),
        migrations.CreateModel(
            name='Os',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True, verbose_name='系统名称')),
            ],
            options={
                'verbose_name_plural': '操作系统表',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True, verbose_name='来源')),
            ],
            options={
                'verbose_name_plural': '主机来源表',
            },
        ),
        migrations.AddField(
            model_name='host',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mydjangoapp.Lable', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='host',
            name='logining',
            field=models.ManyToManyField(blank=True, null=True, to='Mydjangoapp.Login', verbose_name='授权用户'),
        ),
        migrations.AddField(
            model_name='host',
            name='os',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mydjangoapp.Os', verbose_name='操作系统'),
        ),
        migrations.AddField(
            model_name='host',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qq', to='Mydjangoapp.Source', verbose_name='来源类型'),
        ),
        migrations.AddField(
            model_name='host',
            name='the_upper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upper', to='Mydjangoapp.Host', verbose_name='宿主机'),
        ),
    ]
