# Generated by Django 2.1.4 on 2019-01-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mydjangoapp', '0004_auto_20181230_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='confirmpassword',
            field=models.CharField(default=111, max_length=128),
            preserve_default=False,
        ),
    ]
